### PR TITLE
Adds *must* use routing proxy to guidelines

### LINKED ISSUE #23: Named route helpers should be explicit in which route set is being used
**rationale:** I am writing an engine that use Blacklight views for it's defaults. Within Blacklight, there are views and partials that [call named route helpers without prefixing the `main_app` route set](https://github.com/projectblacklight/blacklight/blob/a9bb717cf1dc5a500194d361c724bec865be0311/app/views/blacklight/nav/_bookmark.html.erb#L1), e.g. `bookmark_path`.

When testing my engine, I was getting `undefined local variable or method 'bookmarks_path'` because it was trying use the routing proxy for my engine, instead of the routing proxy forthe host application.

Rails provides helper methods to the different routing proxies. The default name for the host app's  is `main_app`, and the default for an engine is the same as the engine name, i.e. for `MyEngine`, you can access the routing proxy with `my_engine`. These helpers are available in controllers and views.

I think the incompatibility issue I was having with Blacklight could be alleviated if Blacklight were to explicitly use `main_app.bookmarks_path` in it's views and controllers, instead of just `bookmarks_path`.

**Done when** guideline is accepted or rejected, after discussion.

### PR DESCRIPTION
**Pull request by afred**
Closes #23.

### CODE REVIEW

**Comment by afred** [comment]
@projecthydra-labs/hydra_plugins_wg review and merge?

**Review by jcoyne — DISMISSED** [review]
Can you add justification for this requirement? All routes use a proxy, do you mean the explicit proxy or the implicit proxy?

**Comment by afred** [comment]
@jcoyne justification is [mentioned in the issue comments](https://github.com/projecthydra-labs/hydra_plugins_wg/issues/23#issuecomment-271582178).

Since the the implicit routing proxy changes depending on context, I think it's better if the plugin developer does not assume what that context is.

Perhaps it should be reworded to say:
  > When using URL helpers generated by Rails routes, plugins **should** use the explicit routing helper, and **should not** use the implicit routing helper.

Also, an example of a "good" vs "bad" code snippet here would probably be helpful.

**Comment by jcoyne** [comment]
This goes against idiomatic rails practices :-1:

**Review by jcoyne — COMMENTED** [review]
Justification should go in the commit message rather than an issue so that it's preserved if we ever move off github

**Comment by afred** [comment]
@jcoyne how is it going against idiomatic rails?

**Comment by mbarnett** [comment]
I'd love to see a citation on routing proxies being unidiomatic. It's a solution explicitly endorsed in the Rails Guides.

The major "idiomatic" Rails code bases use it quite a bit. Spree uses it extensively, to point at a well-known example.

**Comment by jcoyne** [comment]
You'll notice that none of the examples here use the explicit `main_app` route proxy: http://guides.rubyonrails.org/routing.html#path-and-url-helpers

> Engines can be considered miniature applications that provide functionality to their host applications. A Rails application is actually just a "supercharged" engine, with the Rails::Application class inheriting a lot of its behavior from Rails::Engine.

- http://guides.rubyonrails.org/engines.html

So, if Rails::Application is a subclass of Rails::Engine, one should always prefix any route helper with `main_app`?  That is not something I'm seeing.

**Comment by afred** [comment]
So...
  * [Rails Guides for Engines](http://guides.rubyonrails.org/engines.html#routes) say to explicitly use the routing proxies, or else you may get unexpected links, or no method errors, but...
  * [Rails Guides for general routing](http://guides.rubyonrails.org/routing.html#path-and-url-helpers) simply do not mention using routing proxies at all.

For plugins that are Engines, I think it's more prudent to follow the Rails docs for Engines, yeah?

I can't think of a situation where it would be safer, or better code, to leave off the routing proxy and just assume that the implicit routing proxy is the one you want.

**Comment by afred** [comment]
@projecthydra-labs/hydra_plugins_wg can we get 👍 or 👎 on this from our group? So far, we have just one, from @mbarnett. Thanks!

**Comment by afred** [comment]
**PR modifications needed:**
  * Justification is added. Basically, something that reiterates and/or refers to the [established guidelines for using routes with Rails Engines](http://guides.rubyonrails.org/engines.html#routes).
  * Change guideline verbiage from
    > Plugins **must** specify...

    to

    > Plugins that are Rails Engines **must** specify..."

**Comment by cjcolvar** [comment]
:+1:

**Pull request merged**
